// <auto-generated />
using System;
using HealthCare.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthCare.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HealthCare.Entities.BenhNhan", b =>
                {
                    b.Property<string>("MaBenhNhan")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BenhManTinh")
                        .HasColumnType("longtext");

                    b.Property<string>("ChongChiDinh")
                        .HasColumnType("longtext");

                    b.Property<string>("DiUng")
                        .HasColumnType("longtext");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<string>("DienThoai")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTrangThai")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhomMau")
                        .HasColumnType("longtext");

                    b.Property<string>("SinhHieu")
                        .HasColumnType("longtext");

                    b.Property<string>("ThuocDangDung")
                        .HasColumnType("longtext");

                    b.Property<string>("TienSuPhauThuat")
                        .HasColumnType("longtext");

                    b.Property<string>("TieuSuBenh")
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThaiHomNay")
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThaiTaiKhoan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaBenhNhan");

                    b.ToTable("benh_nhan");
                });

            modelBuilder.Entity("HealthCare.Entities.ChiTietDichVu", b =>
                {
                    b.Property<string>("MaChiTietDv")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhieuKhamCls")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaChiTietDv");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaPhieuKhamCls");

                    b.ToTable("chi_tiet_dich_vu");
                });

            modelBuilder.Entity("HealthCare.Entities.ChiTietDonThuoc", b =>
                {
                    b.Property<string>("MaChiTietDon")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChiDinhSuDung")
                        .HasColumnType("longtext");

                    b.Property<string>("MaDonThuoc")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaThuoc")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietDon");

                    b.HasIndex("MaDonThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("chi_tiet_don_thuoc");
                });

            modelBuilder.Entity("HealthCare.Entities.DichVuYTe", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiDichVu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaPhongThucHien")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ThoiGianDuKienPhut")
                        .HasColumnType("int");

                    b.HasKey("MaDichVu");

                    b.HasIndex("MaPhongThucHien");

                    b.ToTable("dich_vu_y_te");
                });

            modelBuilder.Entity("HealthCare.Entities.DonThuoc", b =>
                {
                    b.Property<string>("MaDonThuoc")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaBacSiKeDon")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ThoiGianKeDon")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TongTienDon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaDonThuoc");

                    b.HasIndex("MaBacSiKeDon");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("don_thuoc");
                });

            modelBuilder.Entity("HealthCare.Entities.HangDoi", b =>
                {
                    b.Property<string>("MaHangDoi")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("CapCuu")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DoUuTien")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiHangDoi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaChiTietDv")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhieuKham")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nguon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nhan")
                        .HasColumnType("longtext");

                    b.Property<string>("PhanLoaiDen")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiGianCheckin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ThoiGianLichHen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaHangDoi");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaChiTietDv")
                        .IsUnique();

                    b.HasIndex("MaPhieuKham")
                        .IsUnique();

                    b.HasIndex("MaPhong");

                    b.ToTable("hang_doi");
                });

            modelBuilder.Entity("HealthCare.Entities.HoaDonThanhToan", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoaiDotthu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaDonThuoc")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhanSuThu")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhieuKham")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhieuKhamCls")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaDonThuoc")
                        .IsUnique();

                    b.HasIndex("MaNhanSuThu");

                    b.HasIndex("MaPhieuKham")
                        .IsUnique();

                    b.HasIndex("MaPhieuKhamCls")
                        .IsUnique();

                    b.ToTable("hoa_don_thanh_toan");
                });

            modelBuilder.Entity("HealthCare.Entities.KetQuaDichVu", b =>
                {
                    b.Property<string>("MaKetQua")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaChiTietDv")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNguoiTao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NoiDungKetQua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThaiChot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaKetQua");

                    b.HasIndex("MaChiTietDv")
                        .IsUnique();

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("ket_qua_dich_vu");
                });

            modelBuilder.Entity("HealthCare.Entities.KhoThuoc", b =>
                {
                    b.Property<string>("MaThuoc")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CongDung")
                        .HasColumnType("longtext");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("GiaNiemYet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoLo")
                        .HasColumnType("longtext");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaThuoc");

                    b.ToTable("kho_thuoc");
                });

            modelBuilder.Entity("HealthCare.Entities.KhoaChuyenMon", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("longtext");

                    b.Property<string>("DienThoai")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaKhoa");

                    b.ToTable("khoa_chuyen_mon");
                });

            modelBuilder.Entity("HealthCare.Entities.LichHenKham", b =>
                {
                    b.Property<string>("MaLichHen")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("CoHieuLuc")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("GioHen")
                        .HasColumnType("time(6)");

                    b.Property<string>("LoaiHen")
                        .HasColumnType("longtext");

                    b.Property<string>("MaBenhNhan")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaLichTruc")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayHen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenBenhNhan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ThoiLuongPhut")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaLichHen");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaLichTruc");

                    b.ToTable("lich_hen_kham");
                });

            modelBuilder.Entity("HealthCare.Entities.LichTruc", b =>
                {
                    b.Property<string>("MaLichTruc")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CaTruc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time(6)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaYTaTruc")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NghiTruc")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaLichTruc");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaYTaTruc");

                    b.ToTable("lich_truc");
                });

            modelBuilder.Entity("HealthCare.Entities.LuotKhamBenh", b =>
                {
                    b.Property<string>("MaLuotKham")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoaiLuot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaHangDoi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhanSuThucHien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaYTaHoTro")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaLuotKham");

                    b.HasIndex("MaHangDoi")
                        .IsUnique();

                    b.HasIndex("MaNhanSuThucHien");

                    b.HasIndex("MaYTaHoTro");

                    b.ToTable("luot_kham_benh");
                });

            modelBuilder.Entity("HealthCare.Entities.NhanVienYTe", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("longtext");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChuyenMon")
                        .HasColumnType("longtext");

                    b.Property<string>("DienThoai")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HocVi")
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiYTa")
                        .HasColumnType("longtext");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThaiCongTac")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaKhoa");

                    b.ToTable("nhan_vien_y_te");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuChanDoanCuoi", b =>
                {
                    b.Property<string>("MaPhieuChanDoan")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChanDoanCuoi")
                        .HasColumnType("longtext");

                    b.Property<string>("ChanDoanSoBo")
                        .HasColumnType("longtext");

                    b.Property<string>("HuongXuTri")
                        .HasColumnType("longtext");

                    b.Property<string>("LoiKhuyen")
                        .HasColumnType("longtext");

                    b.Property<string>("MaDonThuoc")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhieuKham")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NoiDungKham")
                        .HasColumnType("longtext");

                    b.Property<string>("PhatDoDieuTri")
                        .HasColumnType("longtext");

                    b.HasKey("MaPhieuChanDoan");

                    b.HasIndex("MaDonThuoc")
                        .IsUnique();

                    b.HasIndex("MaPhieuKham")
                        .IsUnique();

                    b.ToTable("phieu_chan_doan_cuoi");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuKhamCanLamSang", b =>
                {
                    b.Property<string>("MaPhieuKhamCls")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("AutoPublishEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("MaPhieuKhamLs")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayGioLap")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaPhieuKhamCls");

                    b.HasIndex("MaPhieuKhamLs")
                        .IsUnique();

                    b.ToTable("phieu_kham_can_lam_sang");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuKhamLamSang", b =>
                {
                    b.Property<string>("MaPhieuKham")
                        .HasColumnType("varchar(255)");

                    b.Property<TimeSpan>("GioLap")
                        .HasColumnType("time(6)");

                    b.Property<string>("HinhThucTiepNhan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaBacSiKham")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaDichVuKham")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaLichHen")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNguoiLap")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhieuKqKhamCls")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrieuChung")
                        .HasColumnType("longtext");

                    b.HasKey("MaPhieuKham");

                    b.HasIndex("MaBacSiKham");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaDichVuKham");

                    b.HasIndex("MaLichHen")
                        .IsUnique();

                    b.HasIndex("MaNguoiLap");

                    b.HasIndex("MaPhieuKqKhamCls")
                        .IsUnique();

                    b.ToTable("phieu_kham_lam_sang");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuTongHopKetQua", b =>
                {
                    b.Property<string>("MaPhieuTongHop")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoaiPhieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaNhanSuXuLy")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhieuKhamCls")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiGianXuLy")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaPhieuTongHop");

                    b.HasIndex("MaNhanSuXuLy");

                    b.HasIndex("MaPhieuKhamCls")
                        .IsUnique();

                    b.ToTable("phieu_tong_hop_ket_qua");
                });

            modelBuilder.Entity("HealthCare.Entities.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("GioDongCua")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("GioMoCua")
                        .HasColumnType("time(6)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaBacSiPhuTrach")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThietBi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ViTri")
                        .HasColumnType("longtext");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaBacSiPhuTrach")
                        .IsUnique();

                    b.HasIndex("MaKhoa");

                    b.ToTable("phong");
                });

            modelBuilder.Entity("HealthCare.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsTrangThai")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReplacedToken")
                        .HasColumnType("longtext");

                    b.Property<string>("RevokedIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ThoiGianThuHoi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("MaNhanVien", "IsTrangThai");

                    b.ToTable("refresh_token");
                });

            modelBuilder.Entity("HealthCare.Entities.ThongBaoHeThong", b =>
                {
                    b.Property<string>("MaThongBao")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DoUuTien")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaLuotKham")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaPhieuKham")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaLuotKham");

                    b.HasIndex("MaPhieuKham");

                    b.ToTable("thong_bao_he_thong");
                });

            modelBuilder.Entity("HealthCare.Entities.ThongBaoNguoiNhan", b =>
                {
                    b.Property<long>("MaTbNguoiNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("MaTbNguoiNhan"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaBenhNhan")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhanSu")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaThongBao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ThoiGianDoc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaTbNguoiNhan");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaNhanSu");

                    b.HasIndex("MaThongBao");

                    b.ToTable("thong_bao_nguoi_nhan");
                });

            modelBuilder.Entity("HealthCare.Entities.ChiTietDichVu", b =>
                {
                    b.HasOne("HealthCare.Entities.DichVuYTe", "DichVuYTe")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.PhieuKhamCanLamSang", "PhieuKhamCanLamSang")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaPhieuKhamCls")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DichVuYTe");

                    b.Navigation("PhieuKhamCanLamSang");
                });

            modelBuilder.Entity("HealthCare.Entities.ChiTietDonThuoc", b =>
                {
                    b.HasOne("HealthCare.Entities.DonThuoc", "DonThuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaDonThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.KhoThuoc", "KhoThuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonThuoc");

                    b.Navigation("KhoThuoc");
                });

            modelBuilder.Entity("HealthCare.Entities.DichVuYTe", b =>
                {
                    b.HasOne("HealthCare.Entities.Phong", "PhongThucHien")
                        .WithMany("DichVuYTes")
                        .HasForeignKey("MaPhongThucHien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongThucHien");
                });

            modelBuilder.Entity("HealthCare.Entities.DonThuoc", b =>
                {
                    b.HasOne("HealthCare.Entities.NhanVienYTe", "BacSiKeDon")
                        .WithMany("DonThuocKe")
                        .HasForeignKey("MaBacSiKeDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.BenhNhan", "BenhNhan")
                        .WithMany("DonThuocs")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSiKeDon");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("HealthCare.Entities.HangDoi", b =>
                {
                    b.HasOne("HealthCare.Entities.BenhNhan", "BenhNhan")
                        .WithMany("HangDois")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.ChiTietDichVu", "ChiTietDichVu")
                        .WithOne("HangDois")
                        .HasForeignKey("HealthCare.Entities.HangDoi", "MaChiTietDv")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.PhieuKhamLamSang", "PhieuKhamLamSang")
                        .WithOne("HangDois")
                        .HasForeignKey("HealthCare.Entities.HangDoi", "MaPhieuKham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.Phong", "Phong")
                        .WithMany("HangDois")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("ChiTietDichVu");

                    b.Navigation("PhieuKhamLamSang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("HealthCare.Entities.HoaDonThanhToan", b =>
                {
                    b.HasOne("HealthCare.Entities.BenhNhan", "BenhNhan")
                        .WithMany("HoaDonThanhToans")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.DonThuoc", "DonThuoc")
                        .WithOne("HoaDonThanhToans")
                        .HasForeignKey("HealthCare.Entities.HoaDonThanhToan", "MaDonThuoc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.NhanVienYTe", "NhanSuThu")
                        .WithMany("HoaDonThu")
                        .HasForeignKey("MaNhanSuThu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.PhieuKhamLamSang", "PhieuKhamLamSang")
                        .WithOne("HoaDonThanhToans")
                        .HasForeignKey("HealthCare.Entities.HoaDonThanhToan", "MaPhieuKham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.PhieuKhamCanLamSang", "PhieuKhamCanLamSang")
                        .WithOne("HoaDonThanhToans")
                        .HasForeignKey("HealthCare.Entities.HoaDonThanhToan", "MaPhieuKhamCls")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BenhNhan");

                    b.Navigation("DonThuoc");

                    b.Navigation("NhanSuThu");

                    b.Navigation("PhieuKhamCanLamSang");

                    b.Navigation("PhieuKhamLamSang");
                });

            modelBuilder.Entity("HealthCare.Entities.KetQuaDichVu", b =>
                {
                    b.HasOne("HealthCare.Entities.ChiTietDichVu", "ChiTietDichVu")
                        .WithOne("KetQuaDichVu")
                        .HasForeignKey("HealthCare.Entities.KetQuaDichVu", "MaChiTietDv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.NhanVienYTe", "NhanVienYTes")
                        .WithMany("KetQuaDichVus")
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietDichVu");

                    b.Navigation("NhanVienYTes");
                });

            modelBuilder.Entity("HealthCare.Entities.LichHenKham", b =>
                {
                    b.HasOne("HealthCare.Entities.BenhNhan", "BenhNhan")
                        .WithMany("LichHenKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.LichTruc", "LichTruc")
                        .WithMany("LichHenKhams")
                        .HasForeignKey("MaLichTruc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("LichTruc");
                });

            modelBuilder.Entity("HealthCare.Entities.LichTruc", b =>
                {
                    b.HasOne("HealthCare.Entities.Phong", "Phong")
                        .WithMany("LichTrucs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.NhanVienYTe", "YTaTruc")
                        .WithMany("LichTrucsYTa")
                        .HasForeignKey("MaYTaTruc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("YTaTruc");
                });

            modelBuilder.Entity("HealthCare.Entities.LuotKhamBenh", b =>
                {
                    b.HasOne("HealthCare.Entities.HangDoi", "HangDoi")
                        .WithOne("LuotKhamBenh")
                        .HasForeignKey("HealthCare.Entities.LuotKhamBenh", "MaHangDoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.NhanVienYTe", "NhanSuThucHien")
                        .WithMany("LuotKhamThucHien")
                        .HasForeignKey("MaNhanSuThucHien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.NhanVienYTe", "YTaHoTro")
                        .WithMany("LuotKhamYTaHoTro")
                        .HasForeignKey("MaYTaHoTro")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HangDoi");

                    b.Navigation("NhanSuThucHien");

                    b.Navigation("YTaHoTro");
                });

            modelBuilder.Entity("HealthCare.Entities.NhanVienYTe", b =>
                {
                    b.HasOne("HealthCare.Entities.KhoaChuyenMon", "KhoaChuyenMon")
                        .WithMany("NhanVienYTes")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaChuyenMon");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuChanDoanCuoi", b =>
                {
                    b.HasOne("HealthCare.Entities.DonThuoc", "DonThuoc")
                        .WithOne("PhieuChanDoanCuoi")
                        .HasForeignKey("HealthCare.Entities.PhieuChanDoanCuoi", "MaDonThuoc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.PhieuKhamLamSang", "PhieuKhamLamSang")
                        .WithOne("PhieuChanDoanCuoi")
                        .HasForeignKey("HealthCare.Entities.PhieuChanDoanCuoi", "MaPhieuKham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonThuoc");

                    b.Navigation("PhieuKhamLamSang");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuKhamCanLamSang", b =>
                {
                    b.HasOne("HealthCare.Entities.PhieuKhamLamSang", "PhieuKhamLamSang")
                        .WithOne("PhieuKhamCanLamSang")
                        .HasForeignKey("HealthCare.Entities.PhieuKhamCanLamSang", "MaPhieuKhamLs")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuKhamLamSang");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuKhamLamSang", b =>
                {
                    b.HasOne("HealthCare.Entities.NhanVienYTe", "BacSiKham")
                        .WithMany("PhieuKhamLamSangKham")
                        .HasForeignKey("MaBacSiKham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.BenhNhan", "BenhNhan")
                        .WithMany("PhieuKhamLamSangs")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.DichVuYTe", "DichVuKham")
                        .WithMany("PhieuKhamLamSangs")
                        .HasForeignKey("MaDichVuKham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.LichHenKham", "LichHenKham")
                        .WithOne("PhieuKhamLamSangs")
                        .HasForeignKey("HealthCare.Entities.PhieuKhamLamSang", "MaLichHen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.NhanVienYTe", "NguoiLap")
                        .WithMany("PhieuKhamLamSangLap")
                        .HasForeignKey("MaNguoiLap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.PhieuTongHopKetQua", "PhieuTongHopKetQua")
                        .WithOne("PhieuKhamLamSang")
                        .HasForeignKey("HealthCare.Entities.PhieuKhamLamSang", "MaPhieuKqKhamCls")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BacSiKham");

                    b.Navigation("BenhNhan");

                    b.Navigation("DichVuKham");

                    b.Navigation("LichHenKham");

                    b.Navigation("NguoiLap");

                    b.Navigation("PhieuTongHopKetQua");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuTongHopKetQua", b =>
                {
                    b.HasOne("HealthCare.Entities.NhanVienYTe", "NhanSuXuLy")
                        .WithMany("PhieuTongHopXuLy")
                        .HasForeignKey("MaNhanSuXuLy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthCare.Entities.PhieuKhamCanLamSang", "PhieuKhamCanLamSang")
                        .WithOne("PhieuTongHopKetQua")
                        .HasForeignKey("HealthCare.Entities.PhieuTongHopKetQua", "MaPhieuKhamCls")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanSuXuLy");

                    b.Navigation("PhieuKhamCanLamSang");
                });

            modelBuilder.Entity("HealthCare.Entities.Phong", b =>
                {
                    b.HasOne("HealthCare.Entities.NhanVienYTe", "BacSiPhuTrach")
                        .WithOne("PhongsPhuTrach")
                        .HasForeignKey("HealthCare.Entities.Phong", "MaBacSiPhuTrach")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.KhoaChuyenMon", "KhoaChuyenMon")
                        .WithMany("Phongs")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSiPhuTrach");

                    b.Navigation("KhoaChuyenMon");
                });

            modelBuilder.Entity("HealthCare.Entities.RefreshToken", b =>
                {
                    b.HasOne("HealthCare.Entities.NhanVienYTe", "NhanVien")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HealthCare.Entities.ThongBaoHeThong", b =>
                {
                    b.HasOne("HealthCare.Entities.LuotKhamBenh", "LuotKhamBenh")
                        .WithMany("ThongBaoHeThongs")
                        .HasForeignKey("MaLuotKham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.PhieuKhamLamSang", "PhieuKhamLamSang")
                        .WithMany("ThongBaoHeThongs")
                        .HasForeignKey("MaPhieuKham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LuotKhamBenh");

                    b.Navigation("PhieuKhamLamSang");
                });

            modelBuilder.Entity("HealthCare.Entities.ThongBaoNguoiNhan", b =>
                {
                    b.HasOne("HealthCare.Entities.BenhNhan", "BenhNhan")
                        .WithMany("ThongBaoNguoiNhans")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.NhanVienYTe", "NhanVienYTe")
                        .WithMany("ThongBaoNguoiNhans")
                        .HasForeignKey("MaNhanSu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthCare.Entities.ThongBaoHeThong", "ThongBaoHeThong")
                        .WithMany("ThongBaoNguoiNhans")
                        .HasForeignKey("MaThongBao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("NhanVienYTe");

                    b.Navigation("ThongBaoHeThong");
                });

            modelBuilder.Entity("HealthCare.Entities.BenhNhan", b =>
                {
                    b.Navigation("DonThuocs");

                    b.Navigation("HangDois");

                    b.Navigation("HoaDonThanhToans");

                    b.Navigation("LichHenKhams");

                    b.Navigation("PhieuKhamLamSangs");

                    b.Navigation("ThongBaoNguoiNhans");
                });

            modelBuilder.Entity("HealthCare.Entities.ChiTietDichVu", b =>
                {
                    b.Navigation("HangDois")
                        .IsRequired();

                    b.Navigation("KetQuaDichVu")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCare.Entities.DichVuYTe", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("PhieuKhamLamSangs");
                });

            modelBuilder.Entity("HealthCare.Entities.DonThuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");

                    b.Navigation("HoaDonThanhToans")
                        .IsRequired();

                    b.Navigation("PhieuChanDoanCuoi")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCare.Entities.HangDoi", b =>
                {
                    b.Navigation("LuotKhamBenh")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCare.Entities.KhoThuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");
                });

            modelBuilder.Entity("HealthCare.Entities.KhoaChuyenMon", b =>
                {
                    b.Navigation("NhanVienYTes");

                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("HealthCare.Entities.LichHenKham", b =>
                {
                    b.Navigation("PhieuKhamLamSangs");
                });

            modelBuilder.Entity("HealthCare.Entities.LichTruc", b =>
                {
                    b.Navigation("LichHenKhams");
                });

            modelBuilder.Entity("HealthCare.Entities.LuotKhamBenh", b =>
                {
                    b.Navigation("ThongBaoHeThongs");
                });

            modelBuilder.Entity("HealthCare.Entities.NhanVienYTe", b =>
                {
                    b.Navigation("DonThuocKe");

                    b.Navigation("HoaDonThu");

                    b.Navigation("KetQuaDichVus");

                    b.Navigation("LichTrucsYTa");

                    b.Navigation("LuotKhamThucHien");

                    b.Navigation("LuotKhamYTaHoTro");

                    b.Navigation("PhieuKhamLamSangKham");

                    b.Navigation("PhieuKhamLamSangLap");

                    b.Navigation("PhieuTongHopXuLy");

                    b.Navigation("PhongsPhuTrach");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ThongBaoNguoiNhans");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuKhamCanLamSang", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("HoaDonThanhToans")
                        .IsRequired();

                    b.Navigation("PhieuTongHopKetQua")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuKhamLamSang", b =>
                {
                    b.Navigation("HangDois")
                        .IsRequired();

                    b.Navigation("HoaDonThanhToans");

                    b.Navigation("PhieuChanDoanCuoi")
                        .IsRequired();

                    b.Navigation("PhieuKhamCanLamSang");

                    b.Navigation("ThongBaoHeThongs");
                });

            modelBuilder.Entity("HealthCare.Entities.PhieuTongHopKetQua", b =>
                {
                    b.Navigation("PhieuKhamLamSang")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCare.Entities.Phong", b =>
                {
                    b.Navigation("DichVuYTes");

                    b.Navigation("HangDois");

                    b.Navigation("LichTrucs");
                });

            modelBuilder.Entity("HealthCare.Entities.ThongBaoHeThong", b =>
                {
                    b.Navigation("ThongBaoNguoiNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
